
public enum Heros {
	DOOMFIST,GENJI,MCREE,PHARAH,REAPER,SOLDIER76,SOMBRA,TRACER,BASTION,HANZO,JUNRAT,MEI,TORBJORN,WIDOWMKER,DVA,ORISA,
	REINHARDTH,ROADHOG,WINSTON,ZARYA,ANA,LUCIO,MERCY,SYMMETRA,ZENYATTA

}
